### PR TITLE
Support Adding and Removing Multiple class in IE11

### PR DESCRIPTION
**Pull request by agubler**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

* Support adding and removing multiple classes in IE11
* Add IE11 to browserstack configuration.
* Added two other fixes for tests in IE11

Resolves https://github.com/dojo/widgets/issues/367

### CODE REVIEW

**Comment by kitsonk** [comment]
Also, I tried this branch and can confirm it resolves the issue.

**Comment by kitsonk** [comment]
I was also thinking is there any benefit to feature detecting the issue and branching... I don't know if there is a huge performance difference between the old path and the new path, but I suspect it every bit can help at the vdom level.  Also, it could become a has flag and be built out/in of builds as well using static optimize.

**Comment by agubler** [comment]
I did think about that when making the change, I have a benchmark taken before the change so can certainly run that again now but I suspect the margins will be neglible.

**Comment by tomdye** [comment]
Good catch

**Pull request merged**
