### PR TITLE
Include Pointer Event Polyfill with Projector

### PR DESCRIPTION
**Pull request by matt-gadd**
**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)

**Description:**

This is to discuss, as its one of the few polyfills we actually have that are external and not from `dojo/shim`. I think we should include it by default in the projector, rather than it being opt-in. We've done similar with css-transitions and the projector, and pepjs is only 6kb min & gzipped.

### CODE REVIEW

**Comment by dylans** [comment]
I agree that we should include it by default as this is not something that someone should need to think about.

**Comment by matt-gadd** [comment]
this will need changes downstream to all the intern configs before it can be taken

**Comment by agubler** [comment]
@matt-gadd is that examples (via the `cli-test-intern` command) and widgets as it stands?

**Comment by matt-gadd** [comment]
@agubler I don't believe `cli-test-intern` needs updating (due to it using webpack), just widgets. Which I think are the following: 
https://github.com/dojo/widgets/blob/master/src/common/tests/intern.ts
https://github.com/dojo/widgets/blob/master/src/dialog/example/index.html
https://github.com/dojo/widgets/blob/master/src/label/example/index.html
https://github.com/dojo/widgets/blob/master/src/slidepane/example/index.html

Which probably further validates the need for https://github.com/dojo/widgets/issues/27

**Comment by agubler** [comment]
@matt-gadd Raised https://github.com/dojo/widgets/pull/62

**Comment by agubler** [comment]
This should be good to go now.

**Pull request merged**
